services:
  - type: web
    name: hydrotech-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: MODEL_URL
        value: https://github.com/adhikaribidita/HydroTech-AI-Flood-Detection/releases/download/v1.0.1/best_model.pth
      - key: EXTRA_CORS_ORIGINS
        sync: false   # set this manually in Render dashboard after Vercel URL is known
